frameworkVersion: ^3.15.2
useDotenv: true

service: serverless-websocket

provider:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}
  name: aws
  runtime: go1.x
  websocketsApiName: ${self:service}
  environment:
    TZ: Asia/Tokyo
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:${env:AWS_ACCOUNT_ID}:table/Connection"
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource:
        - "arn:aws:execute-api:*:*:**/@connections/*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**
functions:
  connectionHandler:
    handler: bin/handleRequest
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    Connection:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Connection
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connection_id
            AttributeType: S
        KeySchema:
          - AttributeName: connection_id
            KeyType: HASH
        SSESpecification:
          SSEEnabled: True
